# Generated by Django 4.2.5 on 2023-11-02 16:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Cars', '0002_alter_car_cat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='cat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Cars.category'),
        ),
    ]
